flush ruleset

table inet oroproxy {
  set authenticated_macs {
    type ether_addr
    flags dynamic
  }

  chain prerouting {
    type nat hook prerouting priority dstnat;
    iif "wlan0" ether saddr != @authenticated_macs tcp dport 80 redirect to :8081
    iif "wlan0" ether saddr != @authenticated_macs tcp dport 443 redirect to :8443
    iif "wlan0" ether saddr @authenticated_macs tcp dport {80,443} redirect to :3128
  }
}
